#!/usr/bin/env python3
"""
This script processes video frames from a directory structure,
converts them to a temporary video, runs the v2e simulation,
converts the v2e output back to frames, and saves them in a new
directory that mirrors the original structure.

Usage:
1. Make sure you have the required libraries installed:
   pip install -r requirements.txt
2. Run the script from your terminal:
   python convert_video.py
"""

import v2e.v2e
import os
import sys
import glob
import cv2
import shutil
import tempfile
import subprocess
from pathlib import Path

# --- CONFIGURATION ---
INPUT_DIR = "DoTA/frames"
OUTPUT_DIR = "v2e_frames"
FRAME_RATE = 10
OVERWRITE_OUTPUT = True

# --- V2E General Options ---
# Set to True to overwrite existing output files in the temporary directory for each video.
V2E_OVERWRITE = True
# Name for the HDF5 events file generated by v2e.
V2E_H5_FILENAME = "events.h5"
# Set to True to skip generating the reconstructed video from DVS events.
# This must be False to get frames as output.
SKIP_VIDEO_OUTPUT = False
# Exposure setting for the DVS video reconstruction.
DVS_EXPOSURE = "duration .1"
# DVS output format.
OUTPUT_MODE = "dvs346"

# --- V2E DVS Model Options ---
# DVS model condition presets: "Clean" or "Noisy". Use "Custom" for manual settings.
V2E_CONDITION = "Clean" 
# Manual DVS parameters (used if V2E_CONDITION is "Custom").
POS_THRES = 0.2
SIGMA_THRES = 0.03
CUTOFF_HZ = 200
LEAK_RATE_HZ = 5.18
SHOT_NOISE_RATE_HZ = 2.716


def find_image_folders(root_dir):
    """Finds all 'images' folders recursively within the root directory."""
    path = os.path.join(root_dir, '**', 'images')
    folders = glob.glob(path, recursive=True)
    print(f"Found {len(folders)} 'images' directories to process.")
    return folders

def create_video_from_frames(image_folder, output_video_path, frame_rate):
    """Creates a video from a folder of sorted JPG images."""
    images = sorted(glob.glob(os.path.join(image_folder, '*.jpg')))
    if not images:
        print(f"No JPG images found in {image_folder}. Skipping.")
        return False

    frame = cv2.imread(images[0])
    height, width, layers = frame.shape
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    video = cv2.VideoWriter(output_video_path, fourcc, frame_rate, (width, height))

    for image in images:
        video.write(cv2.imread(image))

    video.release()
    print(f"Created temporary video: {output_video_path}")
    return True

def run_v2e_processing(input_video, v2e_output_folder):
    """Builds arguments and runs the v2e simulation on a video file."""
    if V2E_CONDITION == "Clean":
        params = (0.2, 0.02, 0, 0, 0)
    elif V2E_CONDITION == "Noisy":
        params = (0.2, 0.05, 30, 0.1, 5)
    else:  # Custom
        params = (POS_THRES, SIGMA_THRES, CUTOFF_HZ, LEAK_RATE_HZ, SHOT_NOISE_RATE_HZ)
    
    pos_thres, sigma_thres, p_cutoff_hz, p_leak_rate_hz, p_shot_noise_rate_hz = params

    v2e_args = [
        "-i", input_video,
        "-o", v2e_output_folder,
        "--dvs_h5", V2E_H5_FILENAME,
        "--dvs_aedat2", "None",
        "--dvs_text", "None",
        "--no_preview",
        f"--{OUTPUT_MODE}",
        "--pos_thres", str(pos_thres),
        "--neg_thres", str(pos_thres),
        "--sigma_thres", str(sigma_thres),
        "--cutoff_hz", str(p_cutoff_hz),
        "--leak_rate_hz", str(p_leak_rate_hz),
        "--shot_noise_rate_hz", str(p_shot_noise_rate_hz),
        "--disable_slomo"
    ]

    if V2E_OVERWRITE:
        v2e_args.append("--overwrite")
    
    if SKIP_VIDEO_OUTPUT:
        v2e_args.append("--skip_video_output")
    else:
        v2e_args.extend(["--dvs_exposure", *DVS_EXPOSURE.split()])

    print(f"Running v2e on {input_video}...")
    # Use sys.executable to ensure we're using the same python interpreter
    # and use -m to run the module directly, which is more robust than
    # relying on the v2e.exe entry point.
    command = [sys.executable, '-m', 'v2e.v2e'] + v2e_args
    try:
        result = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            encoding='utf-8'
        )
        print("v2e stdout:\n" + result.stdout)
        if result.stderr:
            print("v2e stderr:\n" + result.stderr)
    except FileNotFoundError:
        print("❌ Error: 'v2e' command not found.")
        print("Please ensure the v2e library is installed and accessible in your system's PATH.")
        return False
    except subprocess.CalledProcessError as e:
        print(f"❌ An error occurred during v2e processing (exit code {e.returncode}):")
        print("v2e stdout:\n" + e.stdout)
        print("v2e stderr:\n" + e.stderr)
        return False
    except Exception as e:
        print(f"❌ An unexpected error occurred: {e}")
        return False

    print("✅ v2e processing completed successfully.")
    return True


def extract_frames_from_video(video_path, output_folder):
    """Extracts all frames from a video file and saves them as JPG images."""
    if not os.path.exists(video_path):
        print(f"Video file not found at {video_path}. Cannot extract frames.")
        return

    vidcap = cv2.VideoCapture(video_path)
    success, image = vidcap.read()
    count = 0
    while success:
        frame_path = os.path.join(output_folder, f"frame_{count:06d}.jpg")
        cv2.imwrite(frame_path, image)
        success, image = vidcap.read()
        count += 1
    vidcap.release()
    print(f"Extracted {count} frames to {output_folder}")


def main():
    """Main script function to find and process all image sequences."""
    image_folders = find_image_folders(INPUT_DIR)
    
    for image_folder in image_folders:
        print("-" * 50)
        print(f"Processing folder: {image_folder}")

        # Create a corresponding output directory structure
        output_frame_folder = image_folder.replace(INPUT_DIR, OUTPUT_DIR, 1)
        if os.path.exists(output_frame_folder) and OVERWRITE_OUTPUT:
            print(f"Output folder {output_frame_folder} exists. Removing it.")
            shutil.rmtree(output_frame_folder)
        
        Path(output_frame_folder).mkdir(parents=True, exist_ok=True)
        
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_video_path = os.path.join(temp_dir, 'temp_video.mp4')
            
            # 1. Create a temporary video from the image frames
            if not create_video_from_frames(image_folder, temp_video_path, FRAME_RATE):
                continue
            
            # 2. Process the video with v2e
            v2e_output_dir = os.path.join(temp_dir, 'v2e_output')
            Path(v2e_output_dir).mkdir()
            if not run_v2e_processing(temp_video_path, v2e_output_dir):
                print("Skipping frame extraction due to v2e error.")
                continue

            # 3. Extract frames from the v2e reconstructed video
            # v2e saves the reconstructed video as 'dvs-video.avi' by default
            reconstructed_video_path = os.path.join(v2e_output_dir, 'dvs-video.avi')
            extract_frames_from_video(reconstructed_video_path, output_frame_folder)
            
        print(f"✅ Successfully processed and saved frames to {output_frame_folder}")
    
    print("-" * 50)
    print("All folders processed.")

if __name__ == "__main__":
    main()